# netlify.toml

# Base build settings (applies to the frontend)
[build]
  base    = "client/"          # Base directory: Where package.json lives
  publish = "dist/"            # Publish directory relative to base directory (client/dist)
  command = "npm run build"    # Build command

# Functions settings
[functions]
  # Workaround: Use relative path from base directory due to build log interpretation
  directory = "../netlify/functions/" 
  # Specifies that Node.js runtime should bundle dependencies from the root package.json
  node_bundler = "esbuild" # Use esbuild for faster builds

# Redirects and Rewrites
# Make the noaa-pfds function available at /api/noaa-pfds
[[redirects]]
  from = "/api/*"                # Match requests starting with /api/
  to = "/.netlify/functions/:splat" # Map to the corresponding function
  status = 200                   # Respond with 200 status (rewrite, not redirect) 