# netlify.toml

# Build settings (run from root)
[build]
  # base    = "client/"          # Removed base directory setting
  publish = "client/dist/"     # Publish directory relative to root
  command = "npm run build --workspace=client"    # Build client workspace from root

# Functions settings
[functions]
  # Path should be relative to repository root
  directory = "netlify/functions/" 
  # Specifies that Node.js runtime should bundle dependencies from the root package.json
  node_bundler = "esbuild" # Use esbuild for faster builds

# Redirects and Rewrites
# Make the noaa-pfds function available at /api/noaa-pfds
[[redirects]]
  from = "/api/*"                # Match requests starting with /api/
  to = "/.netlify/functions/:splat" # Map to the corresponding function
  status = 200                   # Respond with 200 status (rewrite, not redirect) 